### ISSUE TITLE
Loot table?

### ISSUE THREAD

**Issue by P-UPPY** [izarooni/WzVisualizer#5]
Not too sure if something like this is possible but is it possible to view mob drops using such a visualiser? There isn’t a single MS database that lists the loot table for each mob. There are certain ‘old school’ equips that still drop and I want to be sure that I’m hunting the right mobs. Great tool btw! Thanks.

**Comment by izarooni** [comment]
Hi, glad you like tool! Unfortunately I don't think it's possible to show a drop table with this visualizer. It's also not really meant for that.

Drop tables are unique to each server as they're typically stored in the databases rather than WZ files so it's next to impossible to get access to that data. 

It's possible to read data from the Monster Book because it contains some information on what items certain mobs will drop however that's purely client-sided and up to the server's drop table if that mob should drop the item.

**Comment by P-UPPY** [comment]
Ahh that's such a shame. It's really bugging me that we have no accessible way to find out these things. Completely unrelated but you'll know better than me... what about modern private servers? I've seen a couple advertised that are around v220. However, they both stick to drop rates that are similar to GMS. If there was such a server (relatively up-to-date with incredibly high drop rate multiplier), would that be a _good_ way to check mob drops?

**Comment by izarooni** [comment]
Assuming that they have the same drop tables yes that would be a good way to check. I'm not too sure about modern servers but drop tables are commonly shared between servers and sources so there's a good chance that it will work.
